# Generated by Django 3.2.7 on 2021-09-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTable',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('distance_entity', models.PositiveIntegerField(default=0)),
                ('date_entity', models.DateTimeField()),
            ],
            options={
                'db_table': 'showtable',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShowTableFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(blank=True, choices=[('Название', 'Название'), ('Количество', 'Количество'), ('Расстояние', 'Расстояние')], max_length=10, verbose_name='столбец')),
                ('condition', models.CharField(blank=True, choices=[('Равно', 'Равно'), ('Содержит', 'Содержит'), ('Больше', 'Больше'), ('Меньше', 'Меньше')], max_length=10, verbose_name='условие')),
                ('value_input', models.CharField(blank=True, max_length=10, verbose_name='значение')),
            ],
        ),
    ]
